[svn r1517] Removed run_hlstats_autorestart (this can be accomplished just running "run_hlstats start" every few minutes and redirecting to /dev/null) Updated run_hlstats and run_proxy with variables for daemon filename, conf file and path. Updated run_hlstats_multi with variables for daemon filename and path. Fixed run_hlstats_multi not using the logs directory (#736 and #802) Fixed all daemons to use relative paths now (confdir=.) (#737)
NEW LOG FORMAT:
run_hlstats logs will be in the logs directory as "hlstats_DATEFORMAT"
run_hlstats_multi will be in the logs directory as "multi_DATEFORMAT"
run_proxy will be in the logs directory as "proxy_DATEFORMAT"

diff --git a/scripts/run_hlstats_multi b/scripts/run_hlstats_multi
--- a/scripts/run_hlstats_multi
+++ b/scripts/run_hlstats_multi
@@ -35,35 +35,42 @@
 # For support and installation notes visit http://www.hlxcommunity.com
 
 
-
-# set your correct perl path
-cd /usr/local/games/hlstatsx/perl/
-
 # Define Ports for multiple instances here, be sure that the first Instance has index 0 instead index 1 !
 PORTS[0]=30000
 PORTS[1]=30010
 PORTS[2]=30020
 PORTS[3]=30030
 
+# Set the path to the scripts folder (you should not need to modify this.)
+confdir=.
+# Name of the daemon to run
+daemonfile=hlstats.pl
+
+# verify that we can see the daemon file
+if [ ! -f ${confdir}/${daemonfile} ]; then
+    echo "Can't see the daemon.  (${daemonfile})"
+    exit 1
+fi
+
 function start_process {
  # takes the used port from $1 variable
        PORT=$1
        echo "Starting HLstatsX CE PORT=$PORT...";
        PID=hlstats_$PORT.pid
-       LOG=log_$PORT`date +_%Y%m%d_%H-%M-%S`
+       LOG=logs/multi_$PORT`date +_%Y%m%d_%H-%M-%S`
        if [ -f $PID ]; then
           kill -0 `cat $PID` >/dev/null 2>&1
           if [ "$?" == "0" ]; then
               echo "HLstatsX CE PORT=$PORT already running!"
           else
               rm -rf $PID
-              ./hlstats.pl --port=$PORT >$LOG 2>&1 &
+              ./${daemonfile} --port=$PORT >$LOG 2>&1 &
               echo $! >$PID
               echo "$PID created"
               echo "PORT=$PORT Started successfully"
           fi
        else
-          ./hlstats.pl --port=$PORT >$LOG 2>&1 &
+          ./${daemonfile} --port=$PORT >$LOG 2>&1 &
           echo $! >$PID
           echo "$PID created"
           echo "PORT=$PORT Started successfully"
diff --git a/scripts/run_proxy b/scripts/run_proxy
--- a/scripts/run_proxy
+++ b/scripts/run_proxy
@@ -36,18 +36,19 @@
 
 
 
-# set your correct HLstatsX perl path
-perldir=/usr/local/games/hlstatsx/perl
-cd ${perldir}
+# Set the path to the scripts folder (you should not need to modify this.)
+confdir=.
+# Set the configuration file for the daemon (you should not need to modify this.)
+conffile=proxy.conf
+# Set the filename of the daemon to use (you should not need to modify this.)
+daemonfile=proxy-daemon.pl
+# Set where you want to log to (you should not need to modify this.)
+LOG=${confdir}/logs/proxy`date +_%Y%m%d_%H-%M-%S`
 
-# check if you have a structure for hlstats in your homedir
-# if you have it will try to read the conf from there, else use the default
-# located in /usr/local/games/hlstatsx/perl/proxy.conf
-
-if [[ -d ~/hlstats && -r ~/hlstats/proxy.conf ]];then
-	confdir=~/hlstats
-else
-	confdir=${perldir}
+# verify that we can see the daemon file
+if [ ! -f ${confdir}/${daemonfile} ]; then
+    echo "Can't see the daemon.  (${daemonfile})"
+    exit 1
 fi
 
 # verify that you have write access to the directories
@@ -68,6 +69,11 @@ fi
 
 case "$1" in
    start)
+		# verify that we have a .conf file
+	   if [ ! -f ${confdir}/${conffile} ]; then
+	      echo "You're missing your configuration file.  (${conffile})"
+	      exit 1
+	   fi
        echo "Starting HLstatsX...";
        if [ -f ${confdir}/proxy-daemon.pid ]; then
           kill -0 `cat ${confdir}/proxy-daemon.pid` >/dev/null 2>&1
@@ -75,13 +81,13 @@ case "$1" in
               echo "HLstatsX already running!"
           else
               rm -rf ${confdir}/proxy-daemon.pid
-              ./proxy-daemon.pl --configfile=${confdir}/proxy.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
+              ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
               echo $! >${confdir}/proxy-daemon.pid
               echo "PID file created"
               echo "Started successfully"
           fi
        else
-          ./proxy-daemon.pl --configfile=${confdir}/proxy.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
+          ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
           echo $! >${confdir}/proxy-daemon.pid
           echo "PID file created"
           echo "Started successfully"
@@ -102,7 +108,7 @@ case "$1" in
        kill -9 `cat ${confdir}/proxy-daemon.pid` >/dev/null 2>&1
        if [ "$?" == "0" ]; then
            rm -rf ${confdir}/proxy-daemon.pid
-           ./proxy-daemon.pl --configfile=${confdir}/proxy.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
+           ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
            echo $! >${confdir}/proxy-daemon.pid
            echo "PID file created"
            echo "Restarted successfully"
@@ -111,7 +117,7 @@ case "$1" in
            if [ -f ${confdir}/proxy-daemon.pid ]; then
              rm -rf ${confdir}/proxy-daemon.pid
            fi
-           ./proxy-daemon.pl --configfile=${confdir}/proxy.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
+           ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
            echo $! >${confdir}/proxy-daemon.pid
            echo "PID file created"
            echo "Started successfully"
