[svn r1552] Updated the run_ daemons so they could be used as a startup script in init.d (#861) Fixed some bugs in display on playerinfo_general.php.  Also changed (Unknown) text to (Not Specified) with a link to the help page on how to set these options.  (#869)

diff --git a/scripts/run_hlstats b/scripts/run_hlstats
--- a/scripts/run_hlstats
+++ b/scripts/run_hlstats
@@ -34,16 +34,23 @@
 # 
 # For support and installation notes visit http://www.hlxcommunity.com
 
-
+# If you wish to run this script as a daemon script (in /etc/init.d, etc.)
+# you must configure the "confdir" variable below.
+# The other variables are optional and really should not be modified.
 
 # Set the path to the scripts folder (you should not need to modify this.)
 confdir=.
+
 # Name of configuration file to use (you should not need to modify this.)
 conffile=hlstats.conf
 # Filename of daemon to use (you should not need to modify this.)
 daemonfile=hlstats.pl
 # Set where you want to log to (you should not need to modify this.)
-LOG=${confdir}/logs/hlstats`date +_%Y%m%d_%H-%M-%S`
+logdir=logs
+# Set the format for the log file
+logfile=hlstats`date +_%Y%m%d_%H-%M-%S`
+# Set where to store PID files
+piddir=${confdir}
 
 # verify that you have write access to the directories
 if [ ! -w ${confdir} ]; then
@@ -58,76 +65,87 @@ if [ ! -f ${confdir}/${daemonfile} ]; then
 fi
 
 # verify that you have a logs directory
-if [ ! -d ${confdir}/logs ];then
-	mkdir ${confdir}/logs
+if [ ! -d ${confdir}/${logdir} ]; then
+	mkdir ${confdir}/${logdir}
 fi
 
-if [ ! -w ${confdir}/logs ];then
-	echo "you need write access to ${confdir}/logs"
+if [ ! -w ${confdir}/${logdir} ]; then
+	echo "you need write access to ${confdir}/${logdir}"
 	exit 1
 fi
 
+# Grab the current directory so we can put the user back there!
+origdir=`pwd`
+
+# Move into the configured directory
+cd ${confdir}
+
 case "$1" in
-   start)
-       # verify that we have a .conf file
-       if [ ! -f ${confdir}/${conffile} ]; then
-	      echo "You're missing your configuration file.  (${conffile})"
-	      exit 1
-       fi   
+	start)
+		# verify that we have a .conf file
+		if [ ! -f ${conffile} ]; then
+			echo "You're missing your configuration file.  (${conffile})"
+			exit 1
+		fi   
    
-       echo "Starting HLstatsX...";
-       if [ -f ${confdir}/hlstats.pid ]; then
-          kill -0 `cat ${confdir}/hlstats.pid` >/dev/null 2>&1
-          if [ "$?" == "0" ]; then
-              echo "HLstatsX already running!"
-          else
-              rm -rf ${confdir}/hlstats.pid
-              ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-              echo $! >${confdir}/hlstats.pid
-              echo "PID file created"
-              echo "Started successfully"
-          fi
-       else
-          ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-          echo $! >${confdir}/hlstats.pid
-          echo "PID file created"
-          echo "Started successfully"
-       fi
-     ;;
-   stop)
-       echo "Stopping HLstatsX..."
-       kill -9 `cat ${confdir}/hlstats.pid` >/dev/null 2>&1
-       if [ "$?" == "0" ]; then
-          rm -rf ${confdir}/hlstats.pid
-          echo "Stopped successfully"
-       else
-          echo "No HLstatsX running!"
-       fi
-     ;;
-   restart)
-       echo "Restarting HLstatsX..."
-       kill -9 `cat ${confdir}/hlstats.pid` >/dev/null 2>&1
-       if [ "$?" == "0" ]; then
-           rm -rf ${confdir}/hlstats.pid
-           ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-           echo $! >${confdir}/hlstats.pid
-           echo "PID file created"
-           echo "Restarted successfully"
-       else    
-           echo "HLstatsX"
-           if [ -f ${confdir}/hlstats.pid ]; then
-             rm -rf ${confdir}/hlstats.pid
-           fi
-           ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-           echo $! >${confdir}/hlstats.pid
-           echo "PID file created"
-           echo "Started successfully"
-       fi
-     ;;
+		echo "Starting HLstatsX...";
+		if [ -f ${piddir}/hlstats.pid ]; then
+			kill -0 `cat ${piddir}/hlstats.pid` >/dev/null 2>&1
+			if [ "$?" == "0" ]; then
+				echo "HLstatsX already running!"
+			else
+				rm -rf ${piddir}/hlstats.pid
+				./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+				echo $! >${piddir}/hlstats.pid
+				echo "PID file created"
+				echo "Started successfully"
+			fi
+		else
+			./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+			echo $! >${piddir}/hlstats.pid
+			echo "PID file created"
+			echo "Started successfully"
+		fi
+	;;
+	
+	stop)
+		echo "Stopping HLstatsX..."
+		kill -9 `cat ${piddir}/hlstats.pid` >/dev/null 2>&1
+		if [ "$?" == "0" ]; then
+			rm -rf ${piddir}/hlstats.pid
+			echo "Stopped successfully"
+		else
+			echo "No HLstatsX running!"
+		fi
+	;;
+	
+	restart)
+		echo "Restarting HLstatsX..."
+		kill -9 `cat ${piddir}/hlstats.pid` >/dev/null 2>&1
+       
+		if [ "$?" == "0" ]; then
+			rm -rf ${piddir}/hlstats.pid
+			./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+			echo $! >${piddir}/hlstats.pid
+			echo "PID file created"
+			echo "Restarted successfully"
+		else    
+			echo "HLstatsX"
+			if [ -f ${piddir}/hlstats.pid ]; then
+				rm -rf ${piddir}/hlstats.pid
+			fi
+			./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+			echo $! >${piddir}/hlstats.pid
+			echo "PID file created"
+			echo "Started successfully"
+		fi
+	;;
+	
    *)
-       echo "Usage: ./run_hlstats [ start | stop | restart ]"
-     ;;
+		echo "Usage: ./run_hlstats [ start | stop | restart ]"
+	;;
 esac
 
-#
+# Return to the original directory
+cd ${origdir}
 exit 0
diff --git a/scripts/run_proxy b/scripts/run_proxy
--- a/scripts/run_proxy
+++ b/scripts/run_proxy
@@ -34,21 +34,29 @@
 # 
 # For support and installation notes visit http://www.hlxcommunity.com
 
-
+# If you wish to run this script as a daemon script (in /etc/init.d, etc.)
+# you must configure the "confdir" variable below.
+# The other variables are optional and really should not be modified.
 
 # Set the path to the scripts folder (you should not need to modify this.)
 confdir=.
+
 # Set the configuration file for the daemon (you should not need to modify this.)
 conffile=proxy.conf
 # Set the filename of the daemon to use (you should not need to modify this.)
 daemonfile=proxy-daemon.pl
-# Set where you want to log to (you should not need to modify this.)
-LOG=${confdir}/logs/proxy`date +_%Y%m%d_%H-%M-%S`
+# Set where you want to log to.  This is a directory inside of the confdir setting.
+# (You should not need to modify this.)
+logdir=logs
+# Set the format of the log file
+logfile=proxy`date +_%Y%m%d_%H-%M-%S`
+# Set where to store PID files
+piddir=${confdir}
 
 # verify that we can see the daemon file
 if [ ! -f ${confdir}/${daemonfile} ]; then
-    echo "Can't see the daemon.  (${daemonfile})"
-    exit 1
+	echo "Can't see the daemon.  (${daemonfile})"
+	exit 1
 fi
 
 # verify that you have write access to the directories
@@ -58,75 +66,86 @@ if [ ! -w ${confdir} ]; then
 fi
 
 # verify that you have a logs directory
-if [ ! -d ${confdir}/logs ];then
-	mkdir ${confdir}/logs
+if [ ! -d ${confdir}/${logdir} ];then
+	mkdir ${confdir}/${logdir}
 fi
 
-if [ ! -w ${confdir}/logs ];then
-	echo "you need write access to ${confdir}/logs"
+if [ ! -w ${confdir}/${logdir} ];then
+	echo "you need write access to ${confdir}/${logdir}"
 	exit 1
 fi
 
+# Grab out original directory so we can return after
+origdir=`pwd`
+
+# Move into configured directory
+cd ${confdir}
+
 case "$1" in
-   start)
+	start)
 		# verify that we have a .conf file
-	   if [ ! -f ${confdir}/${conffile} ]; then
-	      echo "You're missing your configuration file.  (${conffile})"
-	      exit 1
-	   fi
-       echo "Starting HLstatsX...";
-       if [ -f ${confdir}/proxy-daemon.pid ]; then
-          kill -0 `cat ${confdir}/proxy-daemon.pid` >/dev/null 2>&1
-          if [ "$?" == "0" ]; then
-              echo "HLstatsX already running!"
-          else
-              rm -rf ${confdir}/proxy-daemon.pid
-              ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-              echo $! >${confdir}/proxy-daemon.pid
-              echo "PID file created"
-              echo "Started successfully"
-          fi
-       else
-          ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-          echo $! >${confdir}/proxy-daemon.pid
-          echo "PID file created"
-          echo "Started successfully"
-       fi
-     ;;
-   stop)
-       echo "Stopping HLstatsX..."
-       kill -9 `cat ${confdir}/proxy-daemon.pid` >/dev/null 2>&1
-       if [ "$?" == "0" ]; then
-          rm -rf ${confdir}/proxy-daemon.pid
-          echo "Stopped successfully"
-       else
-          echo "No HLstatsX running!"
-       fi
-     ;;
-   restart)
-       echo "Restarting HLstatsX..."
-       kill -9 `cat ${confdir}/proxy-daemon.pid` >/dev/null 2>&1
-       if [ "$?" == "0" ]; then
-           rm -rf ${confdir}/proxy-daemon.pid
-           ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-           echo $! >${confdir}/proxy-daemon.pid
-           echo "PID file created"
-           echo "Restarted successfully"
-       else    
-           echo "HLstatsX"
-           if [ -f ${confdir}/proxy-daemon.pid ]; then
-             rm -rf ${confdir}/proxy-daemon.pid
-           fi
-           ./${daemonfile} --configfile=${confdir}/${conffile} > $LOG 2>&1 &
-           echo $! >${confdir}/proxy-daemon.pid
-           echo "PID file created"
-           echo "Started successfully"
-       fi
-     ;;
+		if [ ! -f ${conffile} ]; then
+			echo "You're missing your configuration file.  (${conffile})"
+			exit 1
+		fi
+		echo "Starting HLstatsX...";
+		if [ -f ${piddir}/proxy-daemon.pid ]; then
+			kill -0 `cat ${piddir}/proxy-daemon.pid` >/dev/null 2>&1
+			if [ "$?" == "0" ]; then
+				echo "HLstatsX already running!"
+			else
+				rm -rf ${piddir}/proxy-daemon.pid
+				./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+				echo $! >${piddir}/proxy-daemon.pid
+				echo "PID file created"
+				echo "Started successfully"
+			fi
+		else
+			./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+			echo $! >${piddir}/proxy-daemon.pid
+			echo "PID file created"
+			echo "Started successfully"
+		fi
+    ;;
+	
+	stop)
+		echo "Stopping HLstatsX..."
+		kill -9 `cat ${piddir}/proxy-daemon.pid` >/dev/null 2>&1
+		if [ "$?" == "0" ]; then
+			rm -rf ${piddir}/proxy-daemon.pid
+			echo "Stopped successfully"
+		else
+			echo "No HLstatsX running!"
+		fi
+	;;
+
+	restart)
+		echo "Restarting HLstatsX..."
+		kill -9 `cat ${piddir}/proxy-daemon.pid` >/dev/null 2>&1
+		if [ "$?" == "0" ]; then
+			rm -rf ${piddir}/proxy-daemon.pid
+			./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+			echo $! >${piddir}/proxy-daemon.pid
+			echo "PID file created"
+			echo "Restarted successfully"
+		else    
+			echo "HLstatsX"
+			if [ -f ${piddir}/proxy-daemon.pid ]; then
+				rm -rf ${piddir}/proxy-daemon.pid
+			fi
+			./${daemonfile} --configfile=${conffile} > ${logdir}/${logfile} 2>&1 &
+			echo $! >${piddir}/proxy-daemon.pid
+			echo "PID file created"
+			echo "Started successfully"
+		fi
+	;;
+	
    *)
-       echo "Usage: ./run_hlstats [ start | stop | restart ]"
-     ;;
+		echo "Usage: ./run_hlstats [ start | stop | restart ]"
+	;;
 esac
 
-#
+# Return to original directory
+cd ${origdir}
+
 exit 0
